/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LanguageSelector: typeof import('./components/LanguageSelector.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    SelectLangs: typeof import('./components/translate/SelectLangs.vue')['default']
    SelectLanguages: typeof import('./components/SelectLanguages.vue')['default']
    SettingGeneral: typeof import('./components/settings/SettingGeneral.vue')['default']
    Settings: typeof import('./components/settings/Settings.vue')['default']
    SettingsModel: typeof import('./components/settings/SettingsModel.vue')['default']
  }
}
